service:
    name: "ServiceA"

server:
    port: 8080

management:
    health:
        circuitBreakers:
            enabled: true
    endpoints:
        web:
            exposure:
                include: health
    endpoint:
        health:
            show-details: always

resilience4j:
    circuitbreaker:
        instances:
            ServiceA:
                registerHealthIndicator: true
                eventConsumerBufferSize: 10
                failureRateThreshold: 50
                minimumNumberOfCalls: 5
                waitDurationInOpenState: 5s
                automaticTransitionFromOpenToHalfOpenEnabled: true
                permittedNumberOfCallsInHalfOpenState: 3
                slidingWindowType: COUNT_BASED
                slidingWindowSize: 10
retry:
    instances:
        ServiceA:
            registerHealthIndicator: true
            maxRetryAttempts: 3
            waitDuration: 10s

    ratelimiter:
        instances:
            ServiceA:
                registerHealthIndicator: true
                limitForPeriod: 5                # allow 5 requests
                limitRefreshPeriod: 1h          # in 1 hour
                timeoutDuration: 0              # don't wait if limit is hit
